### ISSUE TITLE
BE : 오픈API 이용해 코인정보 가져와 저장

### ISSUE THREAD

**Issue by ShinHB417** [codestates-seb/seb41_main_008#51]
# 현재 진행 중인 작업
- 오픈API 이용해 코인정보 가져와 저장

## TODO

1. [x] 업비트 또는 빗썸 오픈API이용해 데이터 저장
2. [x] DB에 코인정보 저장
3. [x] 실시간 DB 업데이트하며 변경 사항 생길 시 client에게 정보전달

**Comment by ShinHB417** [comment]
## 참고자료
https://okky.kr/articles/1013246
-스케줄링
https://invincure.tistory.com/entry/Java-Quartz-%EC%BF%BC%EC%B8%A0%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EC%97%AC-%EC%9E%90%EB%B0%94-%EC%8A%A4%EC%BC%80%EC%A4%84%EB%A7%81scheduling-%ED%95%98%EA%B8%B0
